### ISSUE TITLE
No graceful handling of non-elf files

### ISSUE THREAD

**Issue by jasonwubz** [jasonwubz/aslr_buster#1]
When a file which is not an elf file such as a plain text file, the exception occurs. Below is a sample output using any plaintext file:

```
readelf: Error: Not an ELF file - it has the wrong magic bytes at the start
Traceback (most recent call last):
  File "../aslr_buster.py", line 84, in <module>
    has_segfault, segfault_address, segfault_offset, effective_payload_file, effective_address_of_string = find_segfault(program_name, 32, probe_mode, max_payload_size, start_payload_name)
  File "/home/jwu/aslr_buster/find_segfault.py", line 96, in find_segfault
    found_rodata, rodata_address, rodata_start, rodata_end = b_handler.search_binary_section(filename, '.rodata')
  File "/home/jwu/aslr_buster/bin_handler.py", line 109, in search_binary_section
    output = subprocess.check_output(command_str, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'readelf -S vuln_01.c' returned non-zero exit status 1.
```

File type checking is needed before this step.

**Comment by jasonwubz** [comment]
Now it will show error similar to the output below for non-elf files:
```
readelf: Error: Not an ELF file - it has the wrong magic bytes at the start
Unable to check architect
Program is not an executable file (ELF), exiting...
```
